version: '3.1'
services:

  redis:
    image: 'redis:7.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  wiremock-leaver-tool-ui:
    image: wiremock/wiremock
    networks:
    - hmpps_int
    restart: on-failure
    ports:
      - "9091:8080"

networks:
  hmpps_int:
