#!/usr/bin/env bash
npm run build
docker-compose down
docker compose -f docker-compose-test.yml down
kill -9 $(lsof -ti:3007)
docker compose -f docker-compose-test.yml up -d
npm run start-e2e & npm run e2e-test-ui