#!/usr/bin/env bash
set -a
source .env
set +a
export CONTENTFUL_ACCESS_TOKEN
export CONTENTFUL_SPACE_ID

npm run build
docker-compose down
docker compose -f docker-compose-test.yml down
kill -9 $(lsof -ti:3007)
docker compose -f docker-compose-test.yml up -d
sleep 5
npm run start-feature &
sleep 5
npm run int-test