#!/usr/bin/env bash
npm run build
docker-compose down
docker compose -f docker-compose-test.yml down
kill -9 $(lsof -ti:3007)
docker compose -f docker-compose-test.yml up -d
npm run start-feature & npm run int-test