version: 2.1

orbs:
 node: circleci/node@4.1.0

parameters:
 dev-auth:
    type: string
    default: "default_dev_auth_value"
 process:
    type: string
    default: "default_process_value"
 node-version:
    type: string
    default: 20.11-browsers

jobs:
 test:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - node/install-packages
      - run: npm install -g k6 && k6 run -e EXECUTION_TYPE=api pt_tests/run.js
        environment:
          DEV_AUTH: <<parameters.dev-auth>>
          PROCESS: <<parameters.process>>

workflows:
 manual_performance_test:
    jobs:
      - test:
          #filters:
          #  branches:
          #    only: main
          #  tags:
          #    only: /^v.*/
            #triggers:
            #  - type: manual
