apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hmpps-resettlement-passport-person-on-probation-ui
  namespace: hmpps-resettlement-passport-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hmpps-resettlement-passport-person-on-probation-ui
  minReplicas: 4
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 95