---
# Per environment values which override defaults in hmpps-resettlement-passport-person-on-probation-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: person-on-probation-user-ui-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://person-on-probation-user-ui-dev.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV

  allowlist: null

generic-prometheus-alerts:
  alertSeverity: resettlement_passport_alerts_non_prod