---
# Per environment values which override defaults in hmpps-resettlement-passport-person-on-probation-ui/values.yaml

generic-service:
  replicaCount: 2

  serviceAccountName: hmpps-resettlement-passport-preprod-irsa
  
  ingress:
    host: person-on-probation-user-ui-preprod.hmpps.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: add_header X-Robots-Tag "noindex, nofollow";
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine DetectionOnly
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=2"

  env:
    INGRESS_URL: "https://person-on-probation-user-ui-preprod.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    GOVUK_ONE_LOGIN_HOME_URL: "https://home.integration.account.gov.uk"
    GOVUK_ONE_LOGIN_URL: "https://oidc.integration.account.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    PSFR_API_URL: "https://resettlement-passport-api-preprod.hmpps.service.justice.gov.uk/resettlement-passport"
    POP_API_URL: "https://person-on-probation-user-api-preprod.hmpps.service.justice.gov.uk/person-on-probation-user"
    GOVUK_ONE_LOGIN_JWKS_URL: "https://oidc.integration.account.gov.uk/.well-known/jwks.json"
    FEATURE_FLAG_ENABLED: "true"

  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons

generic-prometheus-alerts:
  alertSeverity: hmpps-resettlement-passport-non-prod


