---
# Per environment values which override defaults in hmpps-resettlement-passport-person-on-probation-ui/values.yaml

generic-service:
  replicaCount: 2

  serviceAccountName: hmpps-resettlement-passport-dev-irsa
  
  ingress:
    host: person-on-probation-user-ui-dev.hmpps.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: add_header X-Robots-Tag "noindex, nofollow";
      
  env:
    INGRESS_URL: "https://person-on-probation-user-ui-dev.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    GOVUK_ONE_LOGIN_HOME_URL: "https://home.integration.account.gov.uk"
    GOVUK_ONE_LOGIN_URL: "https://oidc.integration.account.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    PSFR_API_URL: "https://resettlement-passport-api-dev.hmpps.service.justice.gov.uk/resettlement-passport"
    POP_API_URL: "https://person-on-probation-user-api-dev.hmpps.service.justice.gov.uk/person-on-probation-user"
    GOVUK_ONE_LOGIN_VTR: "LOW"
    GOVUK_ONE_LOGIN_JWKS_URL: "https://oidc.integration.account.gov.uk/.well-known/jwks.json"
    WEB_SESSION_INACTIVITY_IN_MINUTES: 5
    CONTENTFUL_SHOW_PREVIEW: "true"
    CONTENTFUL_REFRESH_SECONDS: 10
    RATE_LIMIT_PER_MINUTE: 50
    FEATURE_FLAG_ENABLED: "true"

  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons

generic-prometheus-alerts:
  alertSeverity: hmpps-resettlement-passport-non-prod

deploy_grafana_dashboards: true

  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons