---
# Per environment values which override defaults in hmpps-resettlement-passport-person-on-probation-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: person-on-probation-user-ui-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://person-on-probation-user-ui-preprod.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    GOVUK_ONE_LOGIN_URL: "https://oidc.integration.account.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    PSFR_API_URL: "https://resettlement-passport-api-preprod.hmpps.service.justice.gov.uk/resettlement-passport"
    POP_API_URL: "https://person-on-probation-user-api-preprod.hmpps.service.justice.gov.uk/person-on-probation-user"

generic-prometheus-alerts:
  alertSeverity: resettlement_passport_alerts_non_prod
