---
# Per environment values which override defaults in hmpps-resettlement-passport-person-on-probation-ui/values.yaml

generic-service:
  replicaCount: 2
  
  ingress:
    host: person-on-probation-user-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://person-on-probation-user-ui.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    GOVUK_ONE_LOGIN_URL: "https://oidc.integration.account.gov.uk"
    PSFR_API_URL: "https://resettlement-passport-api-prod.hmpps.service.justice.gov.uk/resettlement-passport"
    POP_API_URL: "https://person-on-probation-user-api-prod.hmpps.service.justice.gov.uk/person-on-probation-user"
    APPOINTMENTS_CACHE_IN_MINUTES: 5

generic-prometheus-alerts:
  alertSeverity: resettlement_passport_alerts
