---
# Per environment values which override defaults in hmpps-resettlement-passport-person-on-probation-ui/values.yaml

generic-service:
  ingress:
    host: person-on-probation-user-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://person-on-probation-user-ui.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: resettlement_passport_alerts
